language: node_js
node_js:
 - "10.7"
cache:
  yarn: true
  directories:
    - node_modules
env:
 - CONTENT_DIR="CPS_content/"
before_install:
 - npm install --global gatsby-cli
 - openssl aes-256-cbc -K $encrypted_dbbb8c9e52bb_key -iv $encrypted_dbbb8c9e52bb_iv -in .travis.key.enc -out .travis.key -d
 - chmod 0400 .travis.key
 - GIT_SSH_COMMAND="ssh -i .travis.key" git clone git@github.com:shuttle1987/CPS_content.git
 - cd CPS_content && git log -n 1 --format=%H && cd ..
script:
 - gatsby build
deploy:
 provider: s3
 access_key_id:
  secure: "KcPDdvsUor5PswRBxWEi38OznQXsNRX3LdidQngIg5/nYGJJE4EbNyzFxFhUOXh7rmmhl0KeeLwC+zGQR16a2TlBcWrE5y8itM5ShEy6L4s6E3f90iS39W5Aj5/9awq/5JmZazTnKqLB+ouJxmy4eTpDCbY9a0NSNYuDRopuzj0Fc3skDV5e0sJc/4sz8sxvXZRmcNBgNgHFSYklYZjRC4fxx59RHioWtXu/NYkhGlt35n2Kn4Cai5kKuyrilkdqCUx39GQslw/FbVdB/mYkVjPVSyxQcZyK1LbKI5peLVEFduBMAbgeVeTn0+uuNrHxL9NUmOfgMQUqNeR47eFqSovLuZC4DNCy8Duvi5oHNdy+x/ttT6qdkLuphOrkmktViU88T0pH9eOqKjavC6xydso3pkibRv4VnkCIjnu5jcBu5rWwwGtlBKwSF9dem4rncSHr2DUnfVNOmRujXUKlvQCnUvdDsydp/0a9vq8oKXQ4SWTl1UDaua221rEpEh06+z95q7tz1bxkM1maE3Sj211uz3eU1eewPuep40XGvojrYhpkFpa7QPIxlCyhq142eELY8j0oX1VtMCHmBUtTIPtD2OalrSZtkJjxIBVCovn6k5jk4v7a/RJza/2/k50eQbiFXIFJKvehxs+uoQrq1+eE/AR/SwfaIjUB3uVChmw="
 secret_access_key:
  secure: "Kfv1qO7Hg5iJP+P6qqVLkTa3Kfe1QhziAAhL8GFVRQUzqNAooOmH2LxymgHBu0+9cSHOswBkKSqMeQf26mzkG3u8dbUIfzrbfUzqPai90uLsneNMWWLdlF3joyhUU6uyOBsxEX1+NKOmQ4lMa5LHnCStwOsi8mGKoQMFLqkv9QkA3ASdIfCR7mlAQ53e69Px7fgBzgUZz3ANri/NhcBsWd/ps5PIPL+LASPMSnKAqHflhqZ0VXkM7G8Q3onefBeDt3KZBxn1Jy/dMms1scuD5dGR6Wwjq9hP2AwcTZQtPCnprPtYE+Gu5u0Ytcu/MdDFcj4OAj8YK9VyLZBZzwPvfqu2j1iqTUqVJn6lBPDvoITFUpBlt3rU2z9zy4iMvlIxPYoO6JVq4dmQ0gWaNm6QzLxn8UuuGcw+0Mw90rQKOTFzV9vINoYBsFM+VzqeYeEjKo5J23XfYSjTecgieD1/zo3e/I0d4qjZOabKniffnYFGf3MZJvqKCeB/KwDajspdIGFgdvXsEiLnTKxtizmCXF1vOGXc/88b+TZJCFT9irq4R/Xd5AmjzLf74CUgi9sJL5jmIFVx3iYv1h0abrvK032KHyjHSfNLkH0piye7Fbrne2OfYBFpMgke0V6ZrjW3Jhkh78NVc8DDq74Fx/fm9iIXbel8l4m57zYIt/C2poQ="
 bucket: "www.customprogrammingsolutions.com"
 skip_cleanup: true
 local_dir: public
 detect_encoding: true
 default_text_charset: 'utf-8'
 cache_control: "max-age=300"
